// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ehr/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetPatientEhrsRequest struct {
	PatientId  uint64             `protobuf:"varint,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetPatientEhrsRequest) Reset()         { *m = QueryGetPatientEhrsRequest{} }
func (m *QueryGetPatientEhrsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPatientEhrsRequest) ProtoMessage()    {}
func (*QueryGetPatientEhrsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{2}
}
func (m *QueryGetPatientEhrsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPatientEhrsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPatientEhrsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPatientEhrsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPatientEhrsRequest.Merge(m, src)
}
func (m *QueryGetPatientEhrsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPatientEhrsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPatientEhrsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPatientEhrsRequest proto.InternalMessageInfo

func (m *QueryGetPatientEhrsRequest) GetPatientId() uint64 {
	if m != nil {
		return m.PatientId
	}
	return 0
}

func (m *QueryGetPatientEhrsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPatientEhrsResponse struct {
	// Returning a list of patient's ehrs
	Ehrs []*Ehr `protobuf:"bytes,1,rep,name=ehrs,proto3" json:"ehrs,omitempty"`
	// Adding pagination to response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetPatientEhrsResponse) Reset()         { *m = QueryGetPatientEhrsResponse{} }
func (m *QueryGetPatientEhrsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPatientEhrsResponse) ProtoMessage()    {}
func (*QueryGetPatientEhrsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{3}
}
func (m *QueryGetPatientEhrsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPatientEhrsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPatientEhrsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPatientEhrsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPatientEhrsResponse.Merge(m, src)
}
func (m *QueryGetPatientEhrsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPatientEhrsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPatientEhrsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPatientEhrsResponse proto.InternalMessageInfo

func (m *QueryGetPatientEhrsResponse) GetEhrs() []*Ehr {
	if m != nil {
		return m.Ehrs
	}
	return nil
}

func (m *QueryGetPatientEhrsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPatientEhrsByCreatorRequest struct {
	PatientId  uint64             `protobuf:"varint,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
	Creator    string             `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetPatientEhrsByCreatorRequest) Reset()         { *m = QueryGetPatientEhrsByCreatorRequest{} }
func (m *QueryGetPatientEhrsByCreatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPatientEhrsByCreatorRequest) ProtoMessage()    {}
func (*QueryGetPatientEhrsByCreatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{4}
}
func (m *QueryGetPatientEhrsByCreatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPatientEhrsByCreatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPatientEhrsByCreatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPatientEhrsByCreatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPatientEhrsByCreatorRequest.Merge(m, src)
}
func (m *QueryGetPatientEhrsByCreatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPatientEhrsByCreatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPatientEhrsByCreatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPatientEhrsByCreatorRequest proto.InternalMessageInfo

func (m *QueryGetPatientEhrsByCreatorRequest) GetPatientId() uint64 {
	if m != nil {
		return m.PatientId
	}
	return 0
}

func (m *QueryGetPatientEhrsByCreatorRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *QueryGetPatientEhrsByCreatorRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPatientEhrsByCreatorResponse struct {
	// Returning a list of patient's ehrs
	Ehrs []*Ehr `protobuf:"bytes,1,rep,name=ehrs,proto3" json:"ehrs,omitempty"`
	// Adding pagination to response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetPatientEhrsByCreatorResponse) Reset()         { *m = QueryGetPatientEhrsByCreatorResponse{} }
func (m *QueryGetPatientEhrsByCreatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPatientEhrsByCreatorResponse) ProtoMessage()    {}
func (*QueryGetPatientEhrsByCreatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{5}
}
func (m *QueryGetPatientEhrsByCreatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPatientEhrsByCreatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPatientEhrsByCreatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPatientEhrsByCreatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPatientEhrsByCreatorResponse.Merge(m, src)
}
func (m *QueryGetPatientEhrsByCreatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPatientEhrsByCreatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPatientEhrsByCreatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPatientEhrsByCreatorResponse proto.InternalMessageInfo

func (m *QueryGetPatientEhrsByCreatorResponse) GetEhrs() []*Ehr {
	if m != nil {
		return m.Ehrs
	}
	return nil
}

func (m *QueryGetPatientEhrsByCreatorResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPatientPendingTransferEhrsRequest struct {
	PatientId         uint64 `protobuf:"varint,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
	AuthorizationCode string `protobuf:"bytes,2,opt,name=authorizationCode,proto3" json:"authorizationCode,omitempty"`
}

func (m *QueryGetPatientPendingTransferEhrsRequest) Reset() {
	*m = QueryGetPatientPendingTransferEhrsRequest{}
}
func (m *QueryGetPatientPendingTransferEhrsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetPatientPendingTransferEhrsRequest) ProtoMessage() {}
func (*QueryGetPatientPendingTransferEhrsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{6}
}
func (m *QueryGetPatientPendingTransferEhrsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPatientPendingTransferEhrsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPatientPendingTransferEhrsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPatientPendingTransferEhrsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPatientPendingTransferEhrsRequest.Merge(m, src)
}
func (m *QueryGetPatientPendingTransferEhrsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPatientPendingTransferEhrsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPatientPendingTransferEhrsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPatientPendingTransferEhrsRequest proto.InternalMessageInfo

func (m *QueryGetPatientPendingTransferEhrsRequest) GetPatientId() uint64 {
	if m != nil {
		return m.PatientId
	}
	return 0
}

func (m *QueryGetPatientPendingTransferEhrsRequest) GetAuthorizationCode() string {
	if m != nil {
		return m.AuthorizationCode
	}
	return ""
}

type QueryGetPatientPendingTransferEhrsResponse struct {
	Ehrs []*Ehr `protobuf:"bytes,1,rep,name=ehrs,proto3" json:"ehrs,omitempty"`
}

func (m *QueryGetPatientPendingTransferEhrsResponse) Reset() {
	*m = QueryGetPatientPendingTransferEhrsResponse{}
}
func (m *QueryGetPatientPendingTransferEhrsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryGetPatientPendingTransferEhrsResponse) ProtoMessage() {}
func (*QueryGetPatientPendingTransferEhrsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4cf483915086703, []int{7}
}
func (m *QueryGetPatientPendingTransferEhrsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPatientPendingTransferEhrsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPatientPendingTransferEhrsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPatientPendingTransferEhrsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPatientPendingTransferEhrsResponse.Merge(m, src)
}
func (m *QueryGetPatientPendingTransferEhrsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPatientPendingTransferEhrsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPatientPendingTransferEhrsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPatientPendingTransferEhrsResponse proto.InternalMessageInfo

func (m *QueryGetPatientPendingTransferEhrsResponse) GetEhrs() []*Ehr {
	if m != nil {
		return m.Ehrs
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ashrafmohey.cache.ehr.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ashrafmohey.cache.ehr.QueryParamsResponse")
	proto.RegisterType((*QueryGetPatientEhrsRequest)(nil), "ashrafmohey.cache.ehr.QueryGetPatientEhrsRequest")
	proto.RegisterType((*QueryGetPatientEhrsResponse)(nil), "ashrafmohey.cache.ehr.QueryGetPatientEhrsResponse")
	proto.RegisterType((*QueryGetPatientEhrsByCreatorRequest)(nil), "ashrafmohey.cache.ehr.QueryGetPatientEhrsByCreatorRequest")
	proto.RegisterType((*QueryGetPatientEhrsByCreatorResponse)(nil), "ashrafmohey.cache.ehr.QueryGetPatientEhrsByCreatorResponse")
	proto.RegisterType((*QueryGetPatientPendingTransferEhrsRequest)(nil), "ashrafmohey.cache.ehr.QueryGetPatientPendingTransferEhrsRequest")
	proto.RegisterType((*QueryGetPatientPendingTransferEhrsResponse)(nil), "ashrafmohey.cache.ehr.QueryGetPatientPendingTransferEhrsResponse")
}

func init() { proto.RegisterFile("ehr/query.proto", fileDescriptor_b4cf483915086703) }

var fileDescriptor_b4cf483915086703 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xcd, 0x6e, 0xd3, 0x4e,
	0x14, 0xc5, 0x33, 0xfd, 0xfa, 0xab, 0x53, 0xfd, 0x81, 0x4e, 0x8b, 0x08, 0x6e, 0x63, 0x90, 0x0b,
	0xb4, 0x89, 0xa8, 0x47, 0x09, 0x0b, 0x04, 0x5d, 0x00, 0x89, 0x4a, 0xc5, 0x2e, 0x58, 0xac, 0x10,
	0x9b, 0x49, 0x32, 0xb5, 0x2d, 0x11, 0x8f, 0x3b, 0x9e, 0x00, 0x69, 0x95, 0x4d, 0x9f, 0x00, 0x09,
	0x89, 0x15, 0x12, 0x2b, 0x1e, 0x84, 0x5d, 0x57, 0xa8, 0x12, 0x1b, 0x56, 0x08, 0x25, 0xf0, 0x1e,
	0xc8, 0x33, 0x13, 0xd2, 0x7c, 0x62, 0xc2, 0x82, 0x5d, 0x3d, 0xbe, 0xf7, 0xdc, 0xdf, 0x39, 0x9e,
	0xdb, 0xc0, 0xf3, 0xd4, 0xe3, 0xf8, 0xa0, 0x41, 0x79, 0xd3, 0x0e, 0x39, 0x13, 0x0c, 0x5d, 0x24,
	0x91, 0xc7, 0xc9, 0x7e, 0x9d, 0x79, 0xb4, 0x69, 0x57, 0x49, 0xd5, 0xa3, 0x36, 0xf5, 0xb8, 0xb1,
	0xea, 0x32, 0x97, 0xc9, 0x0a, 0x1c, 0xff, 0xa5, 0x8a, 0x8d, 0x75, 0x97, 0x31, 0xf7, 0x39, 0xc5,
	0x24, 0xf4, 0x31, 0x09, 0x02, 0x26, 0x88, 0xf0, 0x59, 0x10, 0xe9, 0xb7, 0xb9, 0x2a, 0x8b, 0xea,
	0x2c, 0xc2, 0x15, 0x12, 0x51, 0x35, 0x03, 0xbf, 0xc8, 0x57, 0xa8, 0x20, 0x79, 0x1c, 0x12, 0xd7,
	0x0f, 0x64, 0xb1, 0xae, 0xbd, 0x10, 0x73, 0x84, 0x84, 0x93, 0x7a, 0xb7, 0xfb, 0xff, 0xf8, 0x84,
	0x7a, 0x5c, 0x3d, 0x5a, 0xab, 0x10, 0x3d, 0x8e, 0x25, 0xca, 0xb2, 0xc6, 0xa1, 0x07, 0x0d, 0x1a,
	0x09, 0xcb, 0x81, 0x2b, 0x7d, 0xa7, 0x51, 0xc8, 0x82, 0x88, 0xa2, 0x1d, 0xb8, 0xa0, 0xb4, 0xd2,
	0xe0, 0x2a, 0xd8, 0x5a, 0x2a, 0x64, 0xec, 0x91, 0xae, 0x6c, 0xd5, 0x56, 0x9c, 0x3b, 0xf9, 0x7a,
	0x25, 0xe5, 0xe8, 0x16, 0xeb, 0x18, 0x40, 0x43, 0x8a, 0xee, 0x51, 0x51, 0x26, 0xc2, 0xa7, 0x81,
	0xd8, 0xf5, 0x78, 0x77, 0x24, 0x5a, 0x87, 0x8b, 0xa1, 0x3a, 0x7d, 0x54, 0x93, 0xf2, 0x73, 0x4e,
	0xef, 0x00, 0x3d, 0x84, 0xb0, 0xe7, 0x2d, 0x3d, 0x23, 0xa7, 0xdf, 0xb0, 0x55, 0x10, 0x76, 0x1c,
	0x84, 0xad, 0xc2, 0xd6, 0x41, 0xd8, 0x65, 0xe2, 0x52, 0xad, 0xec, 0x9c, 0xe9, 0xb4, 0xde, 0x02,
	0xb8, 0x36, 0x12, 0x42, 0x3b, 0xb4, 0xe1, 0x1c, 0xf5, 0x78, 0xec, 0x6f, 0x76, 0x6b, 0xa9, 0x60,
	0x8c, 0xf1, 0xb7, 0xeb, 0x71, 0x47, 0xd6, 0xa1, 0xbd, 0x11, 0x5c, 0x9b, 0xbf, 0xe5, 0x52, 0xc3,
	0xfa, 0xc0, 0x3e, 0x00, 0xb8, 0x31, 0x02, 0xac, 0xd8, 0x2c, 0x71, 0x4a, 0x04, 0xe3, 0xc9, 0x62,
	0x4a, 0xc3, 0xff, 0xaa, 0xaa, 0x5e, 0xb2, 0x2c, 0x3a, 0xdd, 0xc7, 0x81, 0x00, 0x67, 0xa7, 0x0e,
	0xf0, 0x3d, 0x80, 0xd7, 0x26, 0x73, 0xfe, 0xeb, 0x24, 0x5f, 0xc2, 0xec, 0x00, 0x60, 0x99, 0x06,
	0x35, 0x3f, 0x70, 0x9f, 0x70, 0x12, 0x44, 0xfb, 0x94, 0x27, 0xbf, 0x75, 0x37, 0xe1, 0x32, 0x69,
	0x08, 0x8f, 0x71, 0xff, 0x50, 0x6a, 0x97, 0x58, 0x8d, 0xea, 0x60, 0x87, 0x5f, 0x58, 0xcf, 0x60,
	0x2e, 0xc9, 0xe0, 0xe9, 0xf2, 0x29, 0x7c, 0x9a, 0x87, 0xf3, 0x52, 0x1e, 0x1d, 0xc2, 0x05, 0xb5,
	0x60, 0x28, 0x3b, 0xa6, 0x6b, 0x78, 0xa3, 0x8d, 0x5c, 0x92, 0x52, 0x85, 0x66, 0x5d, 0x3e, 0xfe,
	0xfc, 0xfd, 0xcd, 0xcc, 0x0a, 0x5a, 0xc6, 0xb2, 0x0e, 0xf7, 0xfe, 0x87, 0xa0, 0x77, 0x00, 0x9e,
	0xeb, 0xff, 0xf2, 0x28, 0x3f, 0x49, 0x79, 0xe4, 0xae, 0x1b, 0x85, 0x3f, 0x69, 0xd1, 0x50, 0x1b,
	0x12, 0x2a, 0x83, 0xd6, 0xce, 0x40, 0xc5, 0xc1, 0xe0, 0xa3, 0x5f, 0xdf, 0xab, 0x85, 0x3e, 0x02,
	0x78, 0x69, 0xcc, 0xc5, 0x44, 0x77, 0x93, 0x0f, 0x1d, 0xdc, 0x3a, 0x63, 0x67, 0xaa, 0x5e, 0x4d,
	0xbe, 0x2d, 0xc9, 0x37, 0xd1, 0xf5, 0x09, 0xe4, 0xf8, 0x48, 0x2f, 0x6a, 0x0b, 0xfd, 0x00, 0x30,
	0x33, 0xf1, 0x0a, 0xa1, 0xfb, 0xc9, 0x68, 0xc6, 0x5f, 0x7b, 0xe3, 0xc1, 0x5f, 0x28, 0x68, 0x57,
	0xf7, 0xa4, 0xab, 0x3b, 0xe8, 0xf6, 0xa0, 0xab, 0x50, 0x35, 0xf5, 0xbb, 0x1b, 0xda, 0x96, 0x56,
	0xb1, 0x74, 0xd2, 0x36, 0xc1, 0x69, 0xdb, 0x04, 0xdf, 0xda, 0x26, 0x78, 0xdd, 0x31, 0x53, 0xa7,
	0x1d, 0x33, 0xf5, 0xa5, 0x63, 0xa6, 0x9e, 0x66, 0x5d, 0x5f, 0x78, 0x8d, 0x8a, 0x5d, 0x65, 0x75,
	0xac, 0x38, 0xb7, 0x25, 0xa8, 0x9e, 0xf4, 0x4a, 0xce, 0x12, 0xcd, 0x90, 0x46, 0x95, 0x05, 0xf9,
	0x2b, 0x76, 0xeb, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0xd1, 0xd1, 0x4e, 0x70, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of specific patient's ehrs.
	GetPatientEhrs(ctx context.Context, in *QueryGetPatientEhrsRequest, opts ...grpc.CallOption) (*QueryGetPatientEhrsResponse, error)
	// Queries a list of specific patient's ehr created by specific organization.
	GetPatientEhrsByCreator(ctx context.Context, in *QueryGetPatientEhrsByCreatorRequest, opts ...grpc.CallOption) (*QueryGetPatientEhrsByCreatorResponse, error)
	// Queries a list of specific patient's pending transfer ehrs.
	GetPatientPendingTransferEhrs(ctx context.Context, in *QueryGetPatientPendingTransferEhrsRequest, opts ...grpc.CallOption) (*QueryGetPatientPendingTransferEhrsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ashrafmohey.cache.ehr.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPatientEhrs(ctx context.Context, in *QueryGetPatientEhrsRequest, opts ...grpc.CallOption) (*QueryGetPatientEhrsResponse, error) {
	out := new(QueryGetPatientEhrsResponse)
	err := c.cc.Invoke(ctx, "/ashrafmohey.cache.ehr.Query/GetPatientEhrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPatientEhrsByCreator(ctx context.Context, in *QueryGetPatientEhrsByCreatorRequest, opts ...grpc.CallOption) (*QueryGetPatientEhrsByCreatorResponse, error) {
	out := new(QueryGetPatientEhrsByCreatorResponse)
	err := c.cc.Invoke(ctx, "/ashrafmohey.cache.ehr.Query/GetPatientEhrsByCreator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPatientPendingTransferEhrs(ctx context.Context, in *QueryGetPatientPendingTransferEhrsRequest, opts ...grpc.CallOption) (*QueryGetPatientPendingTransferEhrsResponse, error) {
	out := new(QueryGetPatientPendingTransferEhrsResponse)
	err := c.cc.Invoke(ctx, "/ashrafmohey.cache.ehr.Query/GetPatientPendingTransferEhrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of specific patient's ehrs.
	GetPatientEhrs(context.Context, *QueryGetPatientEhrsRequest) (*QueryGetPatientEhrsResponse, error)
	// Queries a list of specific patient's ehr created by specific organization.
	GetPatientEhrsByCreator(context.Context, *QueryGetPatientEhrsByCreatorRequest) (*QueryGetPatientEhrsByCreatorResponse, error)
	// Queries a list of specific patient's pending transfer ehrs.
	GetPatientPendingTransferEhrs(context.Context, *QueryGetPatientPendingTransferEhrsRequest) (*QueryGetPatientPendingTransferEhrsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetPatientEhrs(ctx context.Context, req *QueryGetPatientEhrsRequest) (*QueryGetPatientEhrsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatientEhrs not implemented")
}
func (*UnimplementedQueryServer) GetPatientEhrsByCreator(ctx context.Context, req *QueryGetPatientEhrsByCreatorRequest) (*QueryGetPatientEhrsByCreatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatientEhrsByCreator not implemented")
}
func (*UnimplementedQueryServer) GetPatientPendingTransferEhrs(ctx context.Context, req *QueryGetPatientPendingTransferEhrsRequest) (*QueryGetPatientPendingTransferEhrsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatientPendingTransferEhrs not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ashrafmohey.cache.ehr.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPatientEhrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPatientEhrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPatientEhrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ashrafmohey.cache.ehr.Query/GetPatientEhrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPatientEhrs(ctx, req.(*QueryGetPatientEhrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPatientEhrsByCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPatientEhrsByCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPatientEhrsByCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ashrafmohey.cache.ehr.Query/GetPatientEhrsByCreator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPatientEhrsByCreator(ctx, req.(*QueryGetPatientEhrsByCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPatientPendingTransferEhrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPatientPendingTransferEhrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPatientPendingTransferEhrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ashrafmohey.cache.ehr.Query/GetPatientPendingTransferEhrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPatientPendingTransferEhrs(ctx, req.(*QueryGetPatientPendingTransferEhrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ashrafmohey.cache.ehr.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetPatientEhrs",
			Handler:    _Query_GetPatientEhrs_Handler,
		},
		{
			MethodName: "GetPatientEhrsByCreator",
			Handler:    _Query_GetPatientEhrsByCreator_Handler,
		},
		{
			MethodName: "GetPatientPendingTransferEhrs",
			Handler:    _Query_GetPatientPendingTransferEhrs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ehr/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPatientEhrsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPatientEhrsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPatientEhrsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.PatientId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PatientId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPatientEhrsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPatientEhrsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPatientEhrsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Ehrs) > 0 {
		for iNdEx := len(m.Ehrs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ehrs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPatientEhrsByCreatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPatientEhrsByCreatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPatientEhrsByCreatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.PatientId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PatientId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPatientEhrsByCreatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPatientEhrsByCreatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPatientEhrsByCreatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Ehrs) > 0 {
		for iNdEx := len(m.Ehrs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ehrs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPatientPendingTransferEhrsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPatientPendingTransferEhrsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPatientPendingTransferEhrsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuthorizationCode) > 0 {
		i -= len(m.AuthorizationCode)
		copy(dAtA[i:], m.AuthorizationCode)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AuthorizationCode)))
		i--
		dAtA[i] = 0x12
	}
	if m.PatientId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PatientId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPatientPendingTransferEhrsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPatientPendingTransferEhrsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPatientPendingTransferEhrsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ehrs) > 0 {
		for iNdEx := len(m.Ehrs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ehrs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPatientEhrsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PatientId != 0 {
		n += 1 + sovQuery(uint64(m.PatientId))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPatientEhrsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ehrs) > 0 {
		for _, e := range m.Ehrs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPatientEhrsByCreatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PatientId != 0 {
		n += 1 + sovQuery(uint64(m.PatientId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPatientEhrsByCreatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ehrs) > 0 {
		for _, e := range m.Ehrs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPatientPendingTransferEhrsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PatientId != 0 {
		n += 1 + sovQuery(uint64(m.PatientId))
	}
	l = len(m.AuthorizationCode)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPatientPendingTransferEhrsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ehrs) > 0 {
		for _, e := range m.Ehrs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPatientEhrsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPatientEhrsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPatientEhrsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PatientId", wireType)
			}
			m.PatientId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PatientId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPatientEhrsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPatientEhrsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPatientEhrsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ehrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ehrs = append(m.Ehrs, &Ehr{})
			if err := m.Ehrs[len(m.Ehrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPatientEhrsByCreatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPatientEhrsByCreatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPatientEhrsByCreatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PatientId", wireType)
			}
			m.PatientId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PatientId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPatientEhrsByCreatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPatientEhrsByCreatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPatientEhrsByCreatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ehrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ehrs = append(m.Ehrs, &Ehr{})
			if err := m.Ehrs[len(m.Ehrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPatientPendingTransferEhrsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPatientPendingTransferEhrsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPatientPendingTransferEhrsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PatientId", wireType)
			}
			m.PatientId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PatientId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizationCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPatientPendingTransferEhrsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPatientPendingTransferEhrsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPatientPendingTransferEhrsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ehrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ehrs = append(m.Ehrs, &Ehr{})
			if err := m.Ehrs[len(m.Ehrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
