// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ehr/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAddEhr struct {
	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PatientId         uint64 `protobuf:"varint,2,opt,name=patientId,proto3" json:"patientId,omitempty"`
	PatientPrivateKey string `protobuf:"bytes,3,opt,name=patientPrivateKey,proto3" json:"patientPrivateKey,omitempty"`
	DataHash          string `protobuf:"bytes,4,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
}

func (m *MsgAddEhr) Reset()         { *m = MsgAddEhr{} }
func (m *MsgAddEhr) String() string { return proto.CompactTextString(m) }
func (*MsgAddEhr) ProtoMessage()    {}
func (*MsgAddEhr) Descriptor() ([]byte, []int) {
	return fileDescriptor_9696955df9818307, []int{0}
}
func (m *MsgAddEhr) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddEhr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddEhr.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddEhr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddEhr.Merge(m, src)
}
func (m *MsgAddEhr) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddEhr) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddEhr.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddEhr proto.InternalMessageInfo

func (m *MsgAddEhr) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddEhr) GetPatientId() uint64 {
	if m != nil {
		return m.PatientId
	}
	return 0
}

func (m *MsgAddEhr) GetPatientPrivateKey() string {
	if m != nil {
		return m.PatientPrivateKey
	}
	return ""
}

func (m *MsgAddEhr) GetDataHash() string {
	if m != nil {
		return m.DataHash
	}
	return ""
}

type MsgAddEhrResponse struct {
	Ehr *Ehr `protobuf:"bytes,1,opt,name=ehr,proto3" json:"ehr,omitempty"`
}

func (m *MsgAddEhrResponse) Reset()         { *m = MsgAddEhrResponse{} }
func (m *MsgAddEhrResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddEhrResponse) ProtoMessage()    {}
func (*MsgAddEhrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9696955df9818307, []int{1}
}
func (m *MsgAddEhrResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddEhrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddEhrResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddEhrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddEhrResponse.Merge(m, src)
}
func (m *MsgAddEhrResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddEhrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddEhrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddEhrResponse proto.InternalMessageInfo

func (m *MsgAddEhrResponse) GetEhr() *Ehr {
	if m != nil {
		return m.Ehr
	}
	return nil
}

type MsgSendIbcTransferEhrs struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Port             string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ChannelID        string `protobuf:"bytes,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TimeoutTimestamp uint64 `protobuf:"varint,4,opt,name=timeoutTimestamp,proto3" json:"timeoutTimestamp,omitempty"`
	PatientId        uint64 `protobuf:"varint,5,opt,name=patientId,proto3" json:"patientId,omitempty"`
}

func (m *MsgSendIbcTransferEhrs) Reset()         { *m = MsgSendIbcTransferEhrs{} }
func (m *MsgSendIbcTransferEhrs) String() string { return proto.CompactTextString(m) }
func (*MsgSendIbcTransferEhrs) ProtoMessage()    {}
func (*MsgSendIbcTransferEhrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_9696955df9818307, []int{2}
}
func (m *MsgSendIbcTransferEhrs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendIbcTransferEhrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendIbcTransferEhrs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendIbcTransferEhrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendIbcTransferEhrs.Merge(m, src)
}
func (m *MsgSendIbcTransferEhrs) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendIbcTransferEhrs) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendIbcTransferEhrs.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendIbcTransferEhrs proto.InternalMessageInfo

func (m *MsgSendIbcTransferEhrs) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendIbcTransferEhrs) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MsgSendIbcTransferEhrs) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *MsgSendIbcTransferEhrs) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

func (m *MsgSendIbcTransferEhrs) GetPatientId() uint64 {
	if m != nil {
		return m.PatientId
	}
	return 0
}

type MsgSendIbcTransferEhrsResponse struct {
}

func (m *MsgSendIbcTransferEhrsResponse) Reset()         { *m = MsgSendIbcTransferEhrsResponse{} }
func (m *MsgSendIbcTransferEhrsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendIbcTransferEhrsResponse) ProtoMessage()    {}
func (*MsgSendIbcTransferEhrsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9696955df9818307, []int{3}
}
func (m *MsgSendIbcTransferEhrsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendIbcTransferEhrsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendIbcTransferEhrsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendIbcTransferEhrsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendIbcTransferEhrsResponse.Merge(m, src)
}
func (m *MsgSendIbcTransferEhrsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendIbcTransferEhrsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendIbcTransferEhrsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendIbcTransferEhrsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgAddEhr)(nil), "ashrafmohey.cache.ehr.MsgAddEhr")
	proto.RegisterType((*MsgAddEhrResponse)(nil), "ashrafmohey.cache.ehr.MsgAddEhrResponse")
	proto.RegisterType((*MsgSendIbcTransferEhrs)(nil), "ashrafmohey.cache.ehr.MsgSendIbcTransferEhrs")
	proto.RegisterType((*MsgSendIbcTransferEhrsResponse)(nil), "ashrafmohey.cache.ehr.MsgSendIbcTransferEhrsResponse")
}

func init() { proto.RegisterFile("ehr/tx.proto", fileDescriptor_9696955df9818307) }

var fileDescriptor_9696955df9818307 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0x36, 0x56, 0x33, 0x2a, 0xd8, 0x11, 0x25, 0x04, 0x09, 0x21, 0x57, 0x55, 0xda,
	0x04, 0x2a, 0x3e, 0x40, 0xd5, 0x82, 0x45, 0x0a, 0x12, 0x7b, 0xe5, 0xdd, 0x34, 0x39, 0xcd, 0x04,
	0x4c, 0x26, 0xcc, 0x4c, 0xa5, 0xc5, 0x67, 0x10, 0xf6, 0x49, 0xf6, 0x39, 0xf6, 0xb2, 0x97, 0xbd,
	0x5c, 0xda, 0x17, 0x59, 0x32, 0x6d, 0x53, 0x76, 0x9b, 0xee, 0xb2, 0x77, 0x39, 0x27, 0xff, 0xfc,
	0x73, 0xfe, 0x6f, 0x0e, 0x7e, 0x09, 0x4c, 0x04, 0x6a, 0xe1, 0x17, 0x82, 0x2b, 0x4e, 0xde, 0x52,
	0xc9, 0x04, 0x9d, 0x65, 0x9c, 0xc1, 0xd2, 0x8f, 0x68, 0xc4, 0xc0, 0x07, 0x26, 0xec, 0x57, 0xa5,
	0x08, 0x98, 0xd8, 0xa9, 0xbc, 0xff, 0x08, 0x9b, 0x63, 0x99, 0x0c, 0xe2, 0x78, 0xc8, 0x04, 0xb1,
	0xf0, 0xb3, 0x48, 0x00, 0x55, 0x5c, 0x58, 0xc8, 0x45, 0x1d, 0x33, 0x3c, 0x94, 0xe4, 0x3d, 0x36,
	0x0b, 0xaa, 0x52, 0xc8, 0xd5, 0x28, 0xb6, 0x9e, 0xb8, 0xa8, 0x63, 0x84, 0xc7, 0x06, 0xe9, 0xe2,
	0xf6, 0xbe, 0xf8, 0x29, 0xd2, 0xbf, 0x54, 0xc1, 0x0f, 0x58, 0x5a, 0x4d, 0xed, 0x70, 0xfa, 0x83,
	0xd8, 0xf8, 0x79, 0x4c, 0x15, 0xfd, 0x4e, 0x25, 0xb3, 0x0c, 0x2d, 0xaa, 0x6a, 0x6f, 0x80, 0xdb,
	0xd5, 0x38, 0x21, 0xc8, 0x82, 0xe7, 0x12, 0x48, 0x17, 0x37, 0x81, 0xed, 0x46, 0x7a, 0xd1, 0xb7,
	0xfd, 0xda, 0x60, 0x7e, 0x79, 0xa0, 0x94, 0x79, 0x97, 0x08, 0xbf, 0x1b, 0xcb, 0xe4, 0x17, 0xe4,
	0xf1, 0x68, 0x1a, 0x4d, 0x04, 0xcd, 0xe5, 0x0c, 0xc4, 0x90, 0x09, 0x79, 0x4f, 0x3e, 0x82, 0x8d,
	0x82, 0x0b, 0xa5, 0xa3, 0x99, 0xa1, 0xfe, 0x2e, 0x33, 0x47, 0x8c, 0xe6, 0x39, 0xfc, 0x19, 0x7d,
	0xdb, 0xa7, 0x39, 0x36, 0xc8, 0x47, 0xfc, 0x5a, 0xa5, 0x19, 0xf0, 0xb9, 0x9a, 0xa4, 0x19, 0x48,
	0x45, 0xb3, 0x42, 0xa7, 0x31, 0xc2, 0x93, 0xfe, 0x6d, 0x7a, 0x4f, 0xef, 0xd0, 0xf3, 0x5c, 0xec,
	0xd4, 0xcf, 0x7b, 0x00, 0xd0, 0x5f, 0x23, 0xdc, 0x1c, 0xcb, 0x84, 0x4c, 0x70, 0x6b, 0xff, 0x52,
	0xee, 0x19, 0x0a, 0x15, 0x3c, 0xbb, 0xf3, 0x90, 0xa2, 0xc2, 0xfb, 0x0f, 0xbf, 0xa9, 0x83, 0xd5,
	0x3b, 0x6f, 0x50, 0x23, 0xb7, 0x3f, 0x3f, 0x4a, 0x7e, 0xb8, 0xfc, 0xcb, 0xd7, 0xab, 0x8d, 0x83,
	0x56, 0x1b, 0x07, 0x5d, 0x6f, 0x1c, 0x74, 0xb1, 0x75, 0x1a, 0xab, 0xad, 0xd3, 0x58, 0x6f, 0x9d,
	0xc6, 0xef, 0x0f, 0x49, 0xaa, 0xd8, 0x7c, 0xea, 0x47, 0x3c, 0x0b, 0x76, 0xd6, 0x3d, 0xed, 0x1d,
	0x68, 0xef, 0x60, 0x11, 0xe8, 0x75, 0x5f, 0x16, 0x20, 0xa7, 0x2d, 0xbd, 0xcc, 0x9f, 0x6e, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x4d, 0x86, 0x45, 0x3a, 0x02, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AddEhr(ctx context.Context, in *MsgAddEhr, opts ...grpc.CallOption) (*MsgAddEhrResponse, error)
	SendIbcTransferEhrs(ctx context.Context, in *MsgSendIbcTransferEhrs, opts ...grpc.CallOption) (*MsgSendIbcTransferEhrsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddEhr(ctx context.Context, in *MsgAddEhr, opts ...grpc.CallOption) (*MsgAddEhrResponse, error) {
	out := new(MsgAddEhrResponse)
	err := c.cc.Invoke(ctx, "/ashrafmohey.cache.ehr.Msg/AddEhr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendIbcTransferEhrs(ctx context.Context, in *MsgSendIbcTransferEhrs, opts ...grpc.CallOption) (*MsgSendIbcTransferEhrsResponse, error) {
	out := new(MsgSendIbcTransferEhrsResponse)
	err := c.cc.Invoke(ctx, "/ashrafmohey.cache.ehr.Msg/SendIbcTransferEhrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AddEhr(context.Context, *MsgAddEhr) (*MsgAddEhrResponse, error)
	SendIbcTransferEhrs(context.Context, *MsgSendIbcTransferEhrs) (*MsgSendIbcTransferEhrsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddEhr(ctx context.Context, req *MsgAddEhr) (*MsgAddEhrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEhr not implemented")
}
func (*UnimplementedMsgServer) SendIbcTransferEhrs(ctx context.Context, req *MsgSendIbcTransferEhrs) (*MsgSendIbcTransferEhrsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendIbcTransferEhrs not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddEhr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddEhr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddEhr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ashrafmohey.cache.ehr.Msg/AddEhr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddEhr(ctx, req.(*MsgAddEhr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendIbcTransferEhrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendIbcTransferEhrs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendIbcTransferEhrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ashrafmohey.cache.ehr.Msg/SendIbcTransferEhrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendIbcTransferEhrs(ctx, req.(*MsgSendIbcTransferEhrs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ashrafmohey.cache.ehr.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEhr",
			Handler:    _Msg_AddEhr_Handler,
		},
		{
			MethodName: "SendIbcTransferEhrs",
			Handler:    _Msg_SendIbcTransferEhrs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ehr/tx.proto",
}

func (m *MsgAddEhr) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddEhr) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddEhr) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataHash) > 0 {
		i -= len(m.DataHash)
		copy(dAtA[i:], m.DataHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DataHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PatientPrivateKey) > 0 {
		i -= len(m.PatientPrivateKey)
		copy(dAtA[i:], m.PatientPrivateKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PatientPrivateKey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PatientId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PatientId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddEhrResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddEhrResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddEhrResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Ehr != nil {
		{
			size, err := m.Ehr.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendIbcTransferEhrs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendIbcTransferEhrs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendIbcTransferEhrs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PatientId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PatientId))
		i--
		dAtA[i] = 0x28
	}
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChannelID) > 0 {
		i -= len(m.ChannelID)
		copy(dAtA[i:], m.ChannelID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Port) > 0 {
		i -= len(m.Port)
		copy(dAtA[i:], m.Port)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Port)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendIbcTransferEhrsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendIbcTransferEhrsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendIbcTransferEhrsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddEhr) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PatientId != 0 {
		n += 1 + sovTx(uint64(m.PatientId))
	}
	l = len(m.PatientPrivateKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DataHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddEhrResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ehr != nil {
		l = m.Ehr.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendIbcTransferEhrs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	if m.PatientId != 0 {
		n += 1 + sovTx(uint64(m.PatientId))
	}
	return n
}

func (m *MsgSendIbcTransferEhrsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddEhr) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddEhr: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddEhr: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PatientId", wireType)
			}
			m.PatientId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PatientId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PatientPrivateKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PatientPrivateKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddEhrResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddEhrResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddEhrResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ehr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ehr == nil {
				m.Ehr = &Ehr{}
			}
			if err := m.Ehr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendIbcTransferEhrs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendIbcTransferEhrs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendIbcTransferEhrs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PatientId", wireType)
			}
			m.PatientId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PatientId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendIbcTransferEhrsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendIbcTransferEhrsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendIbcTransferEhrsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
